version: '3.8'

services:
  server1:
    build: .
    container_name: server1
    hostname: server1
    command: sh -c "make clean && make && ./servidor 8080 1 2 172.20.0.11 8080 3 172.20.0.12 8080"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.10

  server2:
    build: .
    container_name: server2
    hostname: server2
    command: sh -c "make && ./servidor 8080 2 1 172.20.0.10 8080 3 172.20.0.12 8080"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.11

  server3:
    build: .
    container_name: server3
    hostname: server3
    command: sh -c "make && ./servidor 8080 3 1 172.20.0.10 8080 2 172.20.0.11 8080"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.12

  client1:
    build: .
    container_name: client1
    hostname: client1
    depends_on:
      - server1
      - server2
      - server3
    # Mantém vivo para teste interativo
    command: sh -c "make && sleep infinity"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.20

  client2:
    build: .
    container_name: client2
    hostname: client2
    depends_on:
      - server1
      - server2
      - server3
    # Mantém vivo para teste interativo
    command: sh -c "make && sleep infinity"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.20.0.21

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16